# Use generic build mode on Ubuntu
image: Ubuntu
build: off

environment:
  CODECOV_TOKEN: 'e8c9686b-658f-4000-ab9c-c72ddfba592a'

# Install scripts. (runs after repo cloning)
install:
  # install modules
  - nvm install 20
  - nvm use 20
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test
  - npm run coverage
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov -t ${CODECOV_TOKEN}
